load("@rules_cc//cc:defs.bzl", "cc_library")
cc_library(
    name = "core_notify",
    srcs = ["core_notify.cpp"],
    hdrs = ["core_notify.hpp"],
    includes = ["."],
    visibility = ["//modules/pico_sdk_support:__subpackages__"],
    deps = [
        "@pico-sdk//src/rp2_common/hardware_timer",
        "@pico-sdk//src/rp2_common/pico_multicore",
    ],
)
