macro(preloadToolchain)
if((NOT PROJECT_IS_TOP_LEVEL) AND (NOT PROJECT_NAME))
if(EXISTS ${PRELOAD_TOOLCHAIN_FILE})
include(${PRELOAD_TOOLCHAIN_FILE})
elseif(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${PRELOAD_TOOLCHAIN_FILE})
 
else()
message(WARNING "PRELOAD Toolchain file not found: ${PRELOAD_TOOLCHAIN_FILE}")
endif()
endif()
endmacro()

macro(postloadToolchain)
if(PROJECT_IS_TOP_LEVEL AND PROJECT_NAME)
if(EXISTS ${POSTLOAD_TOOLCHAIN_FILE})
include(${POSTLOAD_TOOLCHAIN_FILE})
else()
message(WARNING "POSTLOAD Toolchain file not found: ${POSTLOAD_TOOLCHAIN_FILE}")
endif()
endif()
endmacro()

function(setting)
set()
endfunction()
